import type { NextPage } from 'next';
import Head from 'next/head';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';
import AdminMenu from '@/components/layouts/AdminMenu';

const Bookings = () => {
  return (
    <div>
      <Head>
        <title>Bookings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ m: 3 }}>
        <Typography sx={{ m: '20px auto' }}>Bookings </Typography>
      </Box>
    </div>
  );
};
Bookings.getLayout = function getLayout(page: React.ReactElement) {
  return <AdminMenu activeLink="bookings">{page}</AdminMenu>;
};

export default Bookings;
