import Head from 'next/head';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';
import ActionCard from '@/components/dashboard/ActionCard';
import AdminMenu from '@/components/layouts/AdminMenu';
import { useRouter } from 'next/router';
const RoomTypes = () => {
  const router = useRouter();
  const { hotelId, roomTypeId } = router.query;
  const cardData = {
    title: 'room types',
    count: 0,
    actions: [
      {
        name: 'add',
        callback: () => {
          router.push({
            pathname: '/admin/upload/room',
            query: { hotelId, roomTypeId },
          });
        },
      },
    ],
  };

  return (
    <div>
      <Head>
        <title>Room Type</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        component="main"
        sx={{ p: { xs: '20px 0', sm: '20px 16px' }, maxWidth: 1200 }}
      >
        <Box sx={{ p: 2, maxWidth: 'fit-content' }}>
          <ActionCard card={cardData} />
        </Box>
        <Typography sx={{ m: '20px auto' }}>Room Type </Typography>
        {new Array(5).fill(1).map((num, index) => (
          <div
            key={num + index}
            onClick={() =>
              router.push({
                pathname: '/admin/hotel/room-type/rooms',
                query: { hotelId: num + index },
              })
            }
          >
            <h3>Hotel Room Type {num + index}</h3>
          </div>
        ))}
      </Box>
    </div>
  );
};
RoomTypes.getLayout = function getLayout(page: React.ReactElement) {
  return <AdminMenu activeLink="room types">{page}</AdminMenu>;
};

export default RoomTypes;
