import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import Head from 'next/head';
import Typography from '@mui/material/Typography';
import AdminMenu from '@/components/layouts/AdminMenu';
import DashboardCardGrid from '@/components/DashboardCardGrid';
const Rooms = () => {
  const router = useRouter();
  const { hotelId, roomTypeId } = router.query;
  const cardsData = [
    {
      title: 'room',
      count: 0,
      actions: [
        {
          name: 'add',
          callback: () => {
            console.log('adding new room');
          },
        },
      ],
    },
    {
      title: 'bookings',
      count: 0,
      actions: [
        {
          name: 'show',
          callback: () => {
            console.log('showing all bookings');
          },
        },
        {
          name: 'add',
          callback: () => {
            console.log('adding new booking');
          },
        },
      ],
    },
  ];
  return (
    <div>
      <Head>
        <title>Rooms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Typography sx={{ m: '20px auto' }}>Rooms </Typography>
        <DashboardCardGrid cards={cardsData} />
      </main>
    </div>
  );
};
Rooms.getLayout = function getLayout(page: React.ReactElement) {
  return <AdminMenu activeLink="rooms">{page}</AdminMenu>;
};

export default Rooms;
