import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import Head from 'next/head';
import Typography from '@mui/material/Typography';
import AdminMenu from '@/components/layouts/AdminMenu';
import Grid from '@mui/material/Grid';
import ActionCard from '@/components/dashboard/ActionCard';
import Box from '@mui/material/Box';

function ActionCardGrid({
  cards,
}: {
  cards: Array<{
    title: string;
    actions: Array<{ name: string; callback: Function }>;
    count: number;
    color?: string;
  }>;
}) {
  return (
    <Grid
      container
      sx={{
        width: '100%',
        maxWidth: '1000px',
        justifyContent: { xs: 'center', md: 'start' },
        p: 2,
      }}
      spacing={3}
    >
      {cards.map((card) => (
        <Grid
          item
          xs={12}
          md={4}
          lg={3.5}
          key={card.title}
          sx={{
            display: 'flex',
            justifyContent: { sx: 'center', md: 'start' },
          }}
        >
          <ActionCard card={card} />
        </Grid>
      ))}
    </Grid>
  );
}
const Rooms = () => {
  const router = useRouter();
  const { hotelId, roomTypeId } = router.query;
  const cardsData = [
    {
      title: 'room',
      count: 0,
      actions: [
        {
          name: 'add',
          callback: () => {
            console.log('adding new room');
          },
        },
      ],
    },
    {
      title: 'bookings',
      count: 0,
      actions: [
        {
          name: 'show',
          callback: () => {
            console.log('showing all bookings');
          },
        },
        {
          name: 'add',
          callback: () => {
            console.log('adding new booking');
          },
        },
      ],
    },
  ];
  return (
    <div>
      <Head>
        <title>Rooms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        component="main"
        sx={{ p: { xs: '20px 0', sm: '20px 16px' }, maxWidth: 1200 }}
      >
        <Typography sx={{ m: '20px auto' }}>Rooms </Typography>
        <ActionCardGrid cards={cardsData} />
      </Box>
    </div>
  );
};
Rooms.getLayout = function getLayout(page: React.ReactElement) {
  return <AdminMenu activeLink="rooms">{page}</AdminMenu>;
};

export default Rooms;
