import type { NextPage } from 'next';
import React from 'react';
import Typography from '@mui/material/Typography';
import { useRouter } from 'next/router';
import Head from 'next/head';
import AdminMenu from '@/components/layouts/AdminMenu';

const Dashboard: NextPage = () => {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Typography sx={{ m: '20px auto' }}>Room Requests</Typography>
        {new Array(5).fill(1).map((num, index) => (
          <div
            key={num + index}
            onClick={() =>
              router.push({
                pathname: '/admin/hotel',
                query: { hotelId: num + index },
              })
            }
          >
            <h3>Hotel number {num + index}</h3>
          </div>
        ))}
      </main>
    </div>
  );
};
Dashboard.getLayout = function getLayout(page: React.ReactElement) {
  return <AdminMenu activeLink="dashboard">{page}</AdminMenu>;
};
export default Dashboard;
