import Head from 'next/head';
import Image from 'next/image';
import { GetStaticProps } from 'next';
import HotelForm from '../../../components/HotelForm';
import { useMutation } from '@apollo/client';
import {
  CREATE_HOTEL,
  ADD_HOTEL_FEATURES,
  ADD_HOTEL_ADDRESS,
} from '@/queries/index';
import type { Address, Features, Hotel } from '@/interfaces/';
type Option = {
  id: number;
  name: string;
};
const Home = ({
  facilities,
  activities,
  services,
  languages,
  hotelCategories,
}: {
  facilities: Option[];
  activities: Option[];
  services: Option[];
  languages: Option[];
  hotelCategories: Option[];
}): JSX.Element => {
  const [createHotel] = useMutation(CREATE_HOTEL);
  const [addHotelAddress] = useMutation(ADD_HOTEL_FEATURES);
  const [addHotelFeatures] = useMutation(ADD_HOTEL_ADDRESS);

  const onSubmit = async (
    hotelVariables: Hotel,
    featuresVariables: Features,
    addressVariables: Address
  ) => {
    await createHotel({
      variables: hotelVariables,
      onCompleted: (data) => {
        addHotelAddress({
          variables: { ...addressVariables, hotelId: data.id },
        });
        addHotelFeatures({
          variables: { ...featuresVariables, hotelId: data.id },
        });
      },
    });
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HotelForm
          facilities={facilities}
          activities={activities}
          services={services}
          languages={languages}
          hotelCategories={hotelCategories}
          submitHandler={onSubmit}
        />
      </main>
    </div>
  );
};
export default Home;

export const getStaticProps: GetStaticProps = async (context) => {
  // const restrictionsResults = await client.query({
  //   query: GET_ALL_RESTRICTIONS,
  // });
  // const servicesResults = await client.query({ query: GET_ALL_SERVICES });
  // const facilitiesResults = await client.query({ query: GET_ALL_FACILITIES });
  const props = {
    facilities: new Array(6)
      .fill(0)
      .map((_, index) => ({ id: index + 1, name: 'restaurant' })),
    activities: new Array(5)
      .fill(0)
      .map((_, index) => ({ id: index + 1, name: 'marathon' })),
    services: new Array(15)
      .fill(0)
      .map((_, index) => ({ id: index + 1, name: 'room services' })),
    languages: Array(8)
      .fill(0)
      .map((_, index) => ({ id: index + 1, name: 'english' })),
    hotelCategories: Array(8)
      .fill(0)
      .map((_, index) => ({ id: index + 1, name: 'resort' })),
  };
  return {
    // props: {
    //   facilities: facilitiesResults?.data?.allFacilities || [],
    //   restrictions: restrictionsResults?.data?.allRestrictions || [],
    //   services: servicesResults?.data?.allServices || [],
    // },
    props: {
      ...props,
    },
  };
};
