export const facilities = [
  'parking',
  'Airport shuttle',
  'Free parking',
  'wellness center',
  'fitness center',
  'swimming pool',
  'jacuzzi',
  'sauna',
  'jogging trail',
  'tennis cournts',
  'smooking area',
  'Non-smoking rooms',
  'bar',
  'pool-side bar',
  'open-air patio',
  'lounge area',
  'laundry',
  'semi-open restaurant',
  'open restaurant',
  'restaurant',
  'conference room',
  'e-bike rental',
  'horse cart rental',
  'terrance',
  'outdoor terrance',
  'gift shop',
  'public computer',
  'lobby',
  'night club',
  'handicap facilities',
  'elevator',
  'facilies for childrens',
  'beach access',
];

export const services = [
  'free high speed internet (WiFi)',
  'buffet breackfast',
  'dry & cleaning service',
  'city guides',
  'tour & excursions',
  'luggage forwarding',
  'pick-up/drop-off service',
  'outside catering service',
  'babysitting on request',
  '24hrs concierge',
  'concierge',
  'garden',
  'cooking service',
  'vIP room facilities',
  'bar/cafe 24hrs',
  'security 24hrs',
  'room service 24hrs',
  'front desk 24hrs',
  'limousine',
  'gamming area',
  'special staff attention',
  'free snacks and drinks',
  'children activities',
];

export const amenities = [
  'safty deposit box',
  'aire-conditioned',
  'hear dryer',
  'shaving kit',
  'free TV',
  'paid TV',
  'mini bar',
  'telephone',
  'wired internet',
  'in-room dining',
  'in-room pool',
  'in-room jacuzzi',
  'kitchen',
  'living',
  'DVD player',
  'cupboard',
  'coffe maker',
  'desk',
  'chair',
  'dressing table',
  'spectacular view',
  'city view',
  'nature view',
  'hot tub bath',
  'pull-out coutch',
  'bussines center',
  'bathtub & shower',
  'make up/shaving mirror',
  'bathrobes & slippers',
  'bathroom telephone',
  'handicapped accesible',
  'outdoor entrance',
  'balcony',
  'terrace',
  'wholly equipped modern kitchen',
  'office space',
  'fireplace',
  'privet elevator',
  'oversized windows',
  'elegant furnature and bedding',
  'dresser',
  'extra towels, blankets and pillows',
  'iron',
  'basic toiletries',
  'ashtray',
  'amenities',
  'housekeeping supplies',
  'vanity set',
  'sewing kit',
  'first aid box',
];

export const features = [
  'free cancelation',
  'accessible',
  'family friendly',
  'pet friendly',
  'eco friendly ',
  'smoker friendly',
];

export const roomCategories = [
  'single room',
  'double room',
  'twin room',
  'interconnecting room',
  'adjoining room',
  'standar room',
  'hollywood twing room',
  'duplex room',
  'cabana',
  'studio room',
  'parlor',
  'lanai',
  'efficiency room',
  'mini-suit',
  'suit',
  'prcidential suit',
  'penhouse',
  'valla',
  'accesible room',
];

export const bedTypes = [
  'twin',
  'twin XL',
  'full',
  'queen',
  'king',
  'californian king',
  'bunk',
  'triple bunk',
];

export const hotelCategories = [
  'small hotel',
  'dowtown hotel',
  'sub-urban hotel',
  'resort hotel',
  'airpost hotel',
  'motel',
  'flotel',
  'trancient hotel',
  'casino hotel',
  'comertial/business hotel',
  'suite hotel',
  'residencial hotel',
  'bed & breackfast hotel',
  'conference centers',
  'convention hotel',
];
export const activities = [
  'cycling',
  'golf',
  'tennis',
  'fishing',
  'squash',
  'paintball',
  'downhill skiing',
  'indoor cycling',
  'bowling',
  'mountain climbing',
  'paintball',
  'target shooting practice',
  'in-line skating',
  'tandem skydives',
  'karting',
  'hiking',
  'horseback riding',
  'bobsleigh track',
  'playing cards',
  'pool',
  'badminton',
  'chess',
  'crouise',
  'nordic walking',
  'alleppey sight seeing',
  'fort cochin sight seeing',
  'sightseeing balloon flights',
  'sightseeing airplane flights',
];
export const languages = [
  'english',
  'mandarin',
  'hindi',
  'spanish',
  'french',
  'arabic',
  'bengali',
  'russian',
  'indonesian',
];

export const adminUser = {
  firstName: 'Default',
  secondName: 'Admin',
  email: 'admin@hotelBooker.com',
  password: 'admin',
};
