export const facilities = [
  'parking',
  'airport shuttle',
  'free parking',
  'wellness center',
  'fitness center',
  'swimming pool',
  'jacuzzi',
  'sauna',
  'jogging trail',
  'tennis cournts',
  'smooking area',
  'non-smoking rooms',
  'bar',
  'garden',
  'pool-side bar',
  'open-air patio',
  'lounge area',
  'laundry',
  'semi-open restaurant',
  'open restaurant',
  'restaurant',
  'conference room',

  'terrance',
  'outdoor terrance',
  'gift shop',
  'public computer',
  'lobby',
  'night club',
  'handicap facilities',
  'elevator',
  'facilies for childrens',
  'beach access',
  'hair/beauty salon',
  'vIP room facilities',
];

export const services = [
  'free high speed internet (WiFi)',
  'buffet breackfast',
  'dry & cleaning service',
  'city guides',
  'tour & excursions',
  'luggage forwarding',
  'pick-up/drop-off service',

  'outside catering service',
  'babysitting on request',
  'concierge 24hrs',
  'concierge',
  'e-bike rental',
  'horse cart rental',
  'cooking service',

  'special diet meal',
  'coffee house on site',
  'bar/cafe 24hrs',
  'breakfast in the room',
  'security',
  'security 24hrs',
  'room service',
  'room service 24hrs',

  'front desk 24hrs',
  'limousine',
  'gamming area',
  'special staff attention',
  'free snacks and drinks',
  'children activities',
  'wake-up service/alarm clock',
];

export const amenities = [
  'safty deposit box',
  'aire-conditioned',
  'hear dryer',
  'shaving kit',
  'free TV',
  'paid TV',
  'minibar',
  'telephone',
  'wired internet',
  'in-room dining',
  'in-room pool',
  'in-room jacuzzi',
  'kitchen',
  'living',
  'DVD player',
  'cupboard',
  'desk',
  'chairs',
  'dressing table',
  'spectacular view',
  'city view',
  'nature view',
  'hot tub bath',
  'pull-out coutch',
  'bussines center',
  'bathtub & shower',
  'make up/shaving mirror',
  'bathrobes & slippers',
  'bathroom telephone',
  'handicapped accesible',
  'outdoor entrance',
  'balcony',
  'terrace',
  'wholly equipped modern kitchen',
  'office space',
  'fireplace',
  'privet elevator',
  'oversized windows',
  'elegant furnature and bedding',
  'dresser',
  'extra towels, blankets and pillows',
  'iron',
  'basic toiletries',
  'housekeeping supplies',
  'vanity set',
  'sewing kit',
  'first aid box',
  'soundproof',
  'suit press',
  'ironing facilities',
  'heating',
  'carpeted',
  'coffee machine',
];

export const features = [
  'free cancelation',
  'accessible',
  'family friendly',
  'pet friendly',
  'eco friendly ',
  'smoker friendly',
];

export const roomCategories = [
  'single room',
  'double room',
  'twin room',
  'interconnecting room',
  'adjoining room',
  'standar room',
  'hollywood twing room',
  'duplex room',
  'cabana',
  'studio room',
  'parlor',
  'lanai',
  'efficiency room',
  'mini-suite',
  'suite',
  'prcidential suit',
  'penhouse',
  'valla',
  'accesible room',
];

export const bedTypes = [
  'twin',
  'twin XL',
  'full',
  'queen',
  'king',
  'californian king',
  'bunk',
];

export const hotelCategories = [
  'small hotel',
  'dowtown hotel',
  'sub-urban hotel',
  'resort hotel',
  'airpost hotel',
  'motel',
  'flotel',
  'boutique hotel',
  'trancient hotel',
  'casino hotel',
  'beach resort',
  'comertial/business hotel',
  'suite hotel',
  'residencial hotel',
  'bed & breackfast hotel',
  'conference centers',
  'convention hotel',
  'gastro hotel',
  'pop-up hotel',
  'capsule hotel',
  'hotelship',
  'apart-hotel',
  'hostel',
  'serviced apartment',
  'extended-stay hotel',
];
export const activities = [
  'cycling',
  'golf',
  'tennis',
  'fishing',
  'squash',
  'paintball',
  'downhill sking',
  'indoor cycling',
  'bowling',
  'mountain climbing',
  'target shooting practice',
  'in-line skating',
  'tandem skydives',
  'karting',
  'hiking',
  'horseback riding',
  'bobsleigh track',
  'playing cards',
  'pool',
  'badminton',
  'chess',
  'crouise',
  'nordic walking',
  'alleppey sightseeing',
  'fort cochin sight seeing',
  'balloon sightseeing flights',
  'airplane sightseeing flights',
];
export const languages = [
  'english',
  'mandarin',
  'hindi',
  'spanish',
  'french',
  'arabic',
  'bengali',
  'russian',
  'indonesian',
  'estonian',
  'german',
  'portuguese',
];

export const adminUser = {
  firstName: 'Default',
  lastName: 'admin',
  email: 'admin@hotelBooker.com',
  password: 'admin',
};
