import Head from 'next/head';
import { WithLayoutPage } from '@/interfaces/index';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';
import AdminMenu from '@/components/layouts/AdminMenu';

const Bookings: WithLayoutPage = () => {
  return (
    <div>
      <Head>
        <title>Bookings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        sx={{ p: { xs: '16px 0', sm: '20px 16px' }, maxWidth: 1200 }}
        component="main"
      >
        <Typography sx={{ m: '20px auto' }}>Bookings </Typography>
      </Box>
    </div>
  );
};
Bookings.getLayout = function getLayout(page: React.ReactNode) {
  return <AdminMenu activeLink="bookings">{page}</AdminMenu>;
};

export default Bookings;
