import type { NextPage } from 'next';
import Head from 'next/head';
import AdminMenu from '@/components/layouts/AdminMenu';
import Typography from '@mui/material/Typography';
const Guest = () => {
  return (
    <div>
      <Head>
        <title>Guests</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Typography sx={{ m: '20px auto' }}>Guests List</Typography>
      </main>
    </div>
  );
};
Guest.getLayout = function getLayout(page: React.ReactElement) {
  return <AdminMenu activeLink="guests">{page}</AdminMenu>;
};
export default Guest;
