import type { NextPage } from 'next';
import Head from 'next/head';
import AdminMenu from '@/components/layouts/AdminMenu';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';
const Guest = () => {
  return (
    <div>
      <Head>
        <title>Guests</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        component="main"
        sx={{ p: { xs: '20px 0', sm: '20px 16px' }, maxWidth: 1200 }}
      >
        <Typography sx={{ m: '20px auto' }}>Guests List</Typography>
      </Box>
    </div>
  );
};
Guest.getLayout = function getLayout(page: React.ReactElement) {
  return <AdminMenu activeLink="guests">{page}</AdminMenu>;
};
export default Guest;
