import type { NextPage } from 'next';
import Head from 'next/head';
import AdminMenu from '@/components/layouts/AdminMenu';
import Box from '@mui/material/Box';
import CardMedia from '@mui/material/CardMedia';
import Typography from '@mui/material/Typography';
import DashboardCardGrid from '@/components/DashboardCardGrid';
import hotel from '@/mocks/hotel';
import Card from '@mui/material/Card';

const styles = {
  legend: {
    opacity: 0.6,
    fontWeight: 400,
    width: '55%',
  },
};
const features = [
  { title: 'Facilities', items: hotel.facilities },
  { title: 'Services', items: hotel.services },
  { title: 'Activities', items: hotel.activities },
  { title: 'Languages', items: hotel.languages },
];
const HotelAdmin: NextPage = () => {
  const cardsData = [
    {
      title: 'Room types',
      count: 3,
      actions: [
        {
          name: 'view',
          callback: () => {
            console.log('view all room types');
          },
        },
        {
          name: 'add',
          callback: () => {
            console.log('add  room types');
          },
        },
      ],
    },
    {
      title: 'Guests',
      count: 3,
      actions: [
        {
          name: 'view',
          callback: () => {
            console.log('view all guests');
          },
        },
        {
          name: 'add',
          callback: () => {
            console.log('add  guest');
          },
        },
      ],
    },
    {
      title: 'Requests',
      count: 2,
      actions: [
        {
          name: 'view',
          callback: () => {
            console.log('view all requests');
          },
        },
      ],
    },
  ];
  return (
    <div>
      <Head>
        <title>Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box component="main" sx={{ minHeight: '70vh' }}>
        <DashboardCardGrid cards={cardsData} />

        <Box
          sx={{
            width: '100%',
            maxWidth: '1100px',
            display: 'flex',
            flexWrap: 'wrap',
            height: '260px',
            my: 4,
            mx: 'auto',
          }}
        >
          <Card
            sx={{
              maxWidth: '500px',
              width: '100%',
              minWidth: '318px',
              height: 'fit-content',
              m: { sm: 3 },
            }}
          >
            <CardMedia
              component="img"
              alt="frame image"
              height="250"
              sx={{ objectFit: 'cover' }}
              image={hotel.frameImage}
              title="frame image"
            />
          </Card>
          <Box
            sx={{
              py: 2,
              px: 3,
              minWidth: '318px',
              height: 'fit-content',
            }}
          >
            <Typography variant="h6" sx={{ mb: 2 }}>
              Prices
            </Typography>
            <Box sx={{ display: 'flex', gap: 3, mb: 2 }}>
              <Typography sx={styles.legend}>Lowest price</Typography>
              <Typography>USD${hotel.lowestPrice}</Typography>
            </Box>
            <Box sx={{ display: 'flex', gap: 3, mb: 2 }}>
              <Typography sx={styles.legend}>Taxes and Charges</Typography>
              <Typography>USD${hotel.taxesAndCharges}</Typography>
            </Box>
            <Box></Box>
          </Box>
          {features.map((feature) => (
            <Box
              key={feature.title}
              sx={{
                py: 2,
                px: 3,
                width: 'fit-content',
                height: '100%',
                overflow: 'hidden',
              }}
            >
              <Typography variant="h6" sx={{ mb: 2 }}>
                {feature.title}
                <Typography
                  component="span"
                  sx={{ opacity: 0.8, fontSize: '16px' }}
                >
                  {`(${feature.items.length})`}{' '}
                </Typography>
              </Typography>
              {feature.items.map((item) => (
                <Box key={item.id} sx={{ display: 'flex', gap: 3, mb: 2 }}>
                  <Typography>{item.name}</Typography>
                </Box>
              ))}
            </Box>
          ))}
        </Box>
      </Box>
    </div>
  );
};
HotelAdmin.getLayout = function getLayout(page: ReactElement) {
  return <AdminMenu activeLink="hotel">{page}</AdminMenu>;
};

export default HotelAdmin;
