import type { GetServerSideProps, NextApiRequest, NextApiResponse } from 'next';
import { WithLayoutPage } from '@/interfaces/index';
import { GET_ROOM_MODEL_BOOKING_REQUESTS } from '@/queries/index';
import { getUser } from '@/graphql/utils';
import Typography from '@mui/material/Typography';
import AdminMenu from '@/components/layouts/AdminMenu';
import Head from 'next/head';
import Box from '@mui/material/Box';

import { client } from '@/lib/apollo';
const RoomRequests: WithLayoutPage = ({ hotelId, userId, requests }) => {
  console.log(requests);
  return (
    <div>
      <Head>
        <title>Requests</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        sx={{ p: { xs: '16px 0', sm: '20px 16px' }, maxWidth: 1200 }}
        component="main"
      >
        <Typography sx={{ m: '20px auto' }}>Room Requests</Typography>
      </Box>
    </div>
  );
};
RoomRequests.getLayout = function getLayout(page: React.ReactNode) {
  return <AdminMenu activeLink="requests">{page}</AdminMenu>;
};
export default RoomRequests;
export const getServerSideProps: GetServerSideProps = async ({
  req,
  res,
  query,
}: {
  req: NextApiRequest;
  res: NextApiResponse;
  query: {
    hotelId: number;
  };
}) => {
  try {
    const user = await getUser(req, res);
    if (user.role === 'ADMIN') {
      const { data, error } = await client.query({
        query: GET_ROOM_MODEL_BOOKING_REQUESTS,
        variables: { userId: user.id, hotelId: query.hotelId },
      });

      return {
        props: {
          hotelId: query.hotelId,
          userId: user.id,
          requests: data.requests,
        },
      };
    }

    return {
      redirect: {
        permanent: false,
        destination: '/signin',
      },
      props: {},
    };
  } catch (e) {
    console.log(e);

    return {
      // redirect: {
      //   permanent: false,
      //   destination: '/signin',
      // },
      props: {},
    };
  }
};
