import type { NextPage } from 'next';
import Head from 'next/head';
import Typography from '@mui/material/Typography';

const RoomTypes: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Typography sx={{ m: '20px auto' }}>Rooms Types</Typography>
      </main>
    </div>
  );
};

export default RoomTypes;
