import type { NextPage } from 'next';
import Head from 'next/head';
import room from '@/mocks/roomModel';
import Box from '@mui/material/Box';
import DoneIcon from '@mui/icons-material/Done';
import Typography from '@mui/material/Typography';
import TodayIcon from '@mui/icons-material/Today';
import Button from '@mui/material/Button';
import ImageListItem from '@mui/material/ImageListItem';
import ImageList from '@mui/material/ImageList';

import RoomPreferencesIcon from '@mui/icons-material/RoomPreferences';
import BedIcon from '@mui/icons-material/Bed';
import RoomServiceIcon from '@mui/icons-material/RoomService';
import Modal from '../../components/AbailableRoomModal';
import RoomBedsUI from '@/components/RoomBedsUI';
import { useRouter } from 'next/router';
import { useMutation } from '@apollo/client';
import { MAKE_ROOM_CONSULT } from '@/queries/index';
const RoomPage: NextPage = () => {
  const router = useRouter();
  const handleRedirectToHotel = (id: number) => {
    router.push(`/hotel/${id}`);
  };
  const [makeRoomConsult, { data, loading, error }] =
    useMutation(MAKE_ROOM_CONSULT);
  type Room = {
    childrens: number;
    adults: number;
  };
  type Data = {
    checkInDate: string;
    checkOutDate: string;
    rooms: Room[];
  };
  const handleConsutlSubmit = (data: Data) => {
    console.log(data);
    makeRoomConsult({ variables: { ...data, roomModelId: room.id } });
  };

  return (
    <div>
      <Head>
        <title>Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="page">
        <Typography
          variant="h3"
          component="h1"
          onClick={() => handleRedirectToHotel(room.hotelId)}
          sx={{
            fontWeight: 700,
            margin: '0 16px',
            width: 'fit-content',
            textTransform: 'capitalize',
            padding: '10px 0 0',
            cursor: 'pointer',
            '&:hover': {
              color: 'rgb(0 0 0 / 70%)',
              textDecoration: 'underline',
              textUnderlineOffset: '5px',
            },
          }}
        >
          {room.hotel.name}
        </Typography>
        <Typography
          variant="h4"
          component="h2"
          color="primary"
          sx={{
            fontWeight: 700,
            margin: '0 16px',
            width: 'fit-content',
            textTransform: 'capitalize',
            padding: '10px 0 5px',
          }}
        >
          {room.category}
        </Typography>
        <ImageList
          sx={{
            width: '100%',
            maxHeight: '450px',
            overflow: 'hidden',
            objectFit: 'cover',
            objectPosition: 'center bottom',
          }}
          rowHeight={450}
          cols={1}
        >
          <ImageListItem cols={1}>
            <img
              src={`${room.mainImage}?w=248&fit=crop&auto=format`}
              srcSet={`${room.mainImage}?w=248&fit=crop&auto=format&dpr=2 2x`}
              alt={`${room.hotel.name} ${room.category}`}
              loading="lazy"
            />
          </ImageListItem>
        </ImageList>

        <h4 className="price">
          <span> USD${room.lowestPrice}</span>/Night
        </h4>

        <Typography sx={{ margin: '20px 10px' }}>{room.description}</Typography>
        <div className="list">
          <div className="list-item">
            <TodayIcon color="primary" />
            <Typography>
              <span> minimun stays:</span>
              {`  ${room.minimunStays} nights`}
            </Typography>
          </div>
          <div className="list-item">
            <TodayIcon color="primary" />
            <Typography>
              <span>maximun stays:</span>
              {`  ${room.maximunStays} nights`}
            </Typography>
          </div>
        </div>
        <section className="container">
          <Box
            sx={{
              margin: '30px 0',
            }}
          >
            <Box
              sx={{
                display: 'flex',
                gap: '10px',
                alignItems: 'center',
                my: 3,
              }}
            >
              <BedIcon color="primary" />

              <Typography
                variant="h6"
                sx={{
                  fontWeight: 300,
                  textTransform: 'capitalize',
                }}
              >
                Beds
              </Typography>
            </Box>
            <Box
              sx={{
                display: 'flex',
                alignItems: 'center',
                minWidth: 'max-content',
                textTransform: 'capitalize',
                margin: '15px',
              }}
            >
              {RoomBedsUI(room.beds, 'medium')}
            </Box>

            <Box
              sx={{
                display: 'flex',
                gap: '10px',
                alignItems: 'center',
                my: 3,
              }}
            >
              <RoomPreferencesIcon color="primary" />

              <Typography
                variant="h6"
                sx={{
                  fontWeight: 300,
                  textTransform: 'capitalize',
                }}
              >
                Amenities
              </Typography>
            </Box>
            <div className="list">
              {room.amenities.map((item) => (
                <div key={item.id} className="list-item">
                  <DoneIcon fontSize="small" color="secondary" />
                  <Typography>{item.name}</Typography>
                </div>
              ))}
            </div>
            <Box
              sx={{
                display: 'flex',
                gap: '10px',
                alignItems: 'center',
                my: 3,
              }}
            >
              <RoomServiceIcon color="primary" />

              <Typography
                variant="h6"
                sx={{
                  fontWeight: 300,
                  textTransform: 'capitalize',
                }}
              >
                Services
              </Typography>
            </Box>
            <div className="list">
              {room.services.map((item) => (
                <div key={item.id} className="list-item">
                  <DoneIcon fontSize="small" color="secondary" />
                  <Typography>{item.name}</Typography>
                </div>
              ))}
            </div>
          </Box>
          <Modal onSubmit={handleConsutlSubmit}>
            <Button
              sx={{ padding: '10px 20px' }}
              color="secondary"
              variant="contained"
            >
              Check Diponibility
            </Button>
          </Modal>
        </section>
      </main>
      <style jsx>
        {`
          .page {
            max-width: 1000px;
            margin: 20px auto;
          }

          .container {
            padding: 0 10px;
          }
          h5 {
            font-size: 18px;
            margin: 0;
          }
          .price {
            margin: 0 15px 10px 15px;
            margin-left: auto;
            max-width: fit-content;
            display: block;
            padding: 10px;
            font-weight: 200;
            font-size: 22px;
          }
          .price span {
            color: #3f51b5;
            font-weight: 700;
            margin-left: 5px;
          }
          .list {
            display: flex;
            row-gap: 20px;
            column-gap: 150px;
            flex-wrap: wrap;

            padding: 0 10px;
            text-transform: capitalize;
            font-weight: 400;
          }
          span,
          .inportant {
            color: #3f51b5;
          }

          .list-item {
            display: flex;
            gap: 10px;
            align-items: center;
          }

          .list-item p {
            margin: 8px 0;
          }
        `}
      </style>
    </div>
  );
};

export default RoomPage;
