import type { NextPage, GetServerSideProps, NextApiResponse } from 'next';
import React from 'react';
import { client } from '@/lib/apollo';
import Head from 'next/head';
import Box from '@mui/material/Box';
import DoneIcon from '@mui/icons-material/Done';
import Typography from '@mui/material/Typography';
import TodayIcon from '@mui/icons-material/Today';
import Button from '@mui/material/Button';
import ImageListItem from '@mui/material/ImageListItem';
import ImageList from '@mui/material/ImageList';
import { useTheme } from '@mui/material/styles';
import RoomPreferencesIcon from '@mui/icons-material/RoomPreferences';
import BedIcon from '@mui/icons-material/Bed';
import RoomServiceIcon from '@mui/icons-material/RoomService';
import Modal from '@/components/AbailableRoomModal';
import RoomBedsUI from '@/components/RoomBedsUI';
import { Room } from '@/interfaces/index';
import { useRouter } from 'next/router';
import { useMutation } from '@apollo/client';
import { MAKE_ROOM_CONSULT, GET_ROOM_MODEL_BY_ID } from '@/queries/index';
const RoomPage: NextPage = ({ room }: { room: Room }) => {
  const router = useRouter();
  const theme = useTheme();
  const handleRedirectToHotel = (id: number) => {
    router.push(`/hotel/${id}`);
  };
  const [makeRoomConsult, { data, loading, error }] =
    useMutation(MAKE_ROOM_CONSULT);
  type Room = {
    childrens: number;
    adults: number;
  };
  type Data = {
    checkInDate: string;
    checkOutDate: string;
    rooms: Room[];
  };
  const handleConsutlSubmit = async (data: Data) => {
    console.log(data);
    try {
      await makeRoomConsult({ variables: { ...data, roomModelId: room.id } });
    } catch (err) {
      console.log(err);
      console.log(error?.graphQLErrors);
    }
  };
  React.useEffect(() => {
    if (!loading && data?.message) {
      console.log(data);
    }
  }, [loading]);
  return (
    <div>
      <Head>
        <title>Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="page">
        <Typography
          variant="h3"
          component="h1"
          onClick={() => handleRedirectToHotel(room.hotelId)}
          sx={{
            fontWeight: 700,
            margin: '0 16px',
            width: 'fit-content',
            textTransform: 'capitalize',
            padding: '10px 0 0',
            cursor: 'pointer',
            '&:hover': {
              color: 'rgb(0 0 0 / 70%)',
              textDecoration: 'underline',
              textUnderlineOffset: '5px',
            },
          }}
        >
          {room.hotel.name}
        </Typography>
        <Typography
          variant="h4"
          component="h2"
          color="primary"
          sx={{
            fontWeight: 700,
            margin: '0 16px',
            width: 'fit-content',
            textTransform: 'capitalize',
            padding: '10px 0 5px',
          }}
        >
          {room.category}
        </Typography>
        <ImageList
          sx={{
            width: '100%',
            maxHeight: '450px',
            overflow: 'hidden',
            objectFit: 'cover',
            objectPosition: 'center bottom',
          }}
          rowHeight={450}
          cols={1}
        >
          <ImageListItem cols={1}>
            <img
              src={`${room.mainImage}?w=248&fit=crop&auto=format`}
              srcSet={`${room.mainImage}?w=248&fit=crop&auto=format&dpr=2 2x`}
              alt={`${room.hotel.name} ${room.category}`}
              loading="lazy"
            />
          </ImageListItem>
        </ImageList>
        <Typography
          component="h4"
          variant="h5"
          sx={{
            p: '10px',
            fontWeight: 200,
            maxWidth: 'fit-content',
            m: '0 15px 10px auto',
          }}
        >
          From{' '}
          <Typography
            variant="h5"
            component="span"
            sx={{ color: 'primary.main', fontWeight: 700, ml: 1 }}
          >
            USD${room.lowestPrice}
          </Typography>
          /Night
        </Typography>

        <Typography
          componet="pre"
          sx={{ margin: '20px 10px', whiteSpace: 'pre-line' }}
        >
          {room.description}
        </Typography>
        <div className="list">
          <div className="list-item">
            <TodayIcon color="primary" />
            <Typography>
              <span> minimun stays:</span>
              {`  ${room.minimunStays} nights`}
            </Typography>
          </div>
          <div className="list-item">
            <TodayIcon color="primary" />
            <Typography>
              <span>maximun stays:</span>
              {`  ${room.maximunStays} nights`}
            </Typography>
          </div>
        </div>
        <section className="container">
          <Box
            sx={{
              margin: '30px 0',
            }}
          >
            <Box
              sx={{
                display: 'flex',
                gap: '10px',
                alignItems: 'center',
                my: 3,
              }}
            >
              <BedIcon color="primary" />

              <Typography
                variant="h6"
                sx={{
                  fontWeight: 300,
                  textTransform: 'capitalize',
                }}
              >
                Beds
              </Typography>
            </Box>
            <Box
              sx={{
                display: 'flex',
                alignItems: 'center',
                minWidth: 'max-content',
                textTransform: 'capitalize',
                margin: '15px',
              }}
            >
              {RoomBedsUI(room.beds, 'medium')}
            </Box>

            <Box
              sx={{
                display: 'flex',
                gap: '10px',
                alignItems: 'center',
                my: 3,
              }}
            >
              <RoomPreferencesIcon color="primary" />

              <Typography
                variant="h6"
                sx={{
                  fontWeight: 300,
                  textTransform: 'capitalize',
                }}
              >
                Amenities
              </Typography>
            </Box>
            <div className="list">
              {room.amenities.map((item) => (
                <div key={item.id} className="list-item">
                  <DoneIcon
                    fontSize="small"
                    sx={{ color: theme.palette.primary.light }}
                  />
                  <Typography>{item.name}</Typography>
                </div>
              ))}
            </div>
            <Box
              sx={{
                display: 'flex',
                gap: '10px',
                alignItems: 'center',
                my: 3,
              }}
            >
              <RoomServiceIcon color="primary" />

              <Typography
                variant="h6"
                sx={{
                  fontWeight: 300,
                  textTransform: 'capitalize',
                }}
              >
                Services
              </Typography>
            </Box>
            <div className="list">
              {room.services.map((item) => (
                <div key={item.id} className="list-item">
                  <DoneIcon
                    fontSize="small"
                    sx={{ color: theme.palette.primary.light }}
                  />
                  <Typography>{item.name}</Typography>
                </div>
              ))}
            </div>
          </Box>
          <Modal onSubmit={handleConsutlSubmit}>
            <Button
              sx={{ padding: '10px 20px' }}
              color="secondary"
              variant="contained"
            >
              Check Diponibility
            </Button>
          </Modal>
        </section>
      </main>
      <style jsx>
        {`
          .page {
            max-width: 1000px;
            margin: 20px auto;
          }

          .container {
            padding: 0 10px;
          }
          h5 {
            font-size: 18px;
            margin: 0;
          }

          .list {
            display: flex;
            row-gap: 20px;
            column-gap: 150px;
            flex-wrap: wrap;

            padding: 0 10px;
            text-transform: capitalize;
            font-weight: 400;
          }
          span,
          .inportant {
            color: ${theme.palette.primary.main};
          }

          .list-item {
            display: flex;
            gap: 10px;
            align-items: center;
          }

          .list-item p {
            margin: 8px 0;
          }
        `}
      </style>
    </div>
  );
};

export default RoomPage;
export const getServerSideProps: GetServerSideProps = async ({
  query,
  res,
}: {
  query: { id: number };
  res: NextApiResponse;
}) => {
  const { data, error, loading } = await client.query({
    query: GET_ROOM_MODEL_BY_ID,
    variables: { id: query.id },
  });

  if (error) {
    return {
      redirect: {
        permanent: false,
        destination: '/search',
      },
      props: {},
    };
  }

  return {
    props: {
      room: data?.roomModelById,
    },
  };
};
